### PR TITLE
suh dude

### PR DESCRIPTION
**Pull request by gracening**
please accept traitor

### CODE REVIEW

**Comment by meshroom** [comment]
Ready for merging!!! 👍

**Comment by ian952** [comment]
👍

**Comment by yan-zou** [comment]
I got dragged into this meme

**Comment by R-Wang97** [comment]
+1

**Comment by o00o00o** [comment]
this would be a nice feature in the code. looks good to me

**Comment by Denton-L** [comment]
👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍

**Pull request merged**
